notifications:
  email: false
language: ruby
bundler_args: --without development system_tests
sudo: false
before_install: rm Gemfile.lock || true
script: bundle exec rake test
matrix:
  include:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.0
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES=yes FUTURE_PARSER="yes"

deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: "FB+GouH3vel0+lcCFpctGorICXLEEyMa1C7qlJ9IZVBlW59rV/8ZOZg6rYdTGJ5VzSKN2oG/QPnjT//LucGMptjMPJafnXEkBhwP3QBzDdg+LSYjTBov0h8bpIjyycGvGXV5ERVSzSonkJuCdO92/pnP5nMFXGI0NVpvE7v2X1Y="  
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
